### ISSUE TITLE
Proposal: Silent Erroring (when reasonable)

### ISSUE THREAD

**Issue by Nciklol** [TeamAilurus/ailurus#8]
Currently inside of the Message structure we have
```ts
if (!channel)
    throw new Error('Channel not found');
if (!guild)
    throw new Error('Guild not found');
if (!user)
    throw new Error('User not found');
```

This currently crashes any bot because we don't actually cache guilds, but in the future if a bot is slash commands only (without bot scope) this will also crash the bot, despite there being no actual problem with the code. We should probably make these errors optional.

Could be a opt-in clientoption or an opt-out one.

**Comment by twisttaan** [comment]
merged
